"""Add UserRole enum and role column

Revision ID: 7af1e84d83bc
Revises: 0001
Create Date: 2026-03-01 20:11:28.570278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7af1e84d83bc'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('spotify_playlists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # Explicitly create the enum type for PostgreSQL
    userrole_enum = postgresql.ENUM('user', 'admin', name='userrole')
    userrole_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('role', userrole_enum, server_default='user', nullable=False))
    op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'role')
    
    # Explicitly drop the enum type
    userrole_enum = postgresql.ENUM('user', 'admin', name='userrole')
    userrole_enum.drop(op.get_bind())

    op.alter_column('spotify_playlists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
